In [1]:
%run "countries spoken.ipynb"

In [2]:
files=np.empty(0).astype(str)
for i in range(0,len(session_years)):
    files=np.append(files,[session_dir[i]+"/"+os.listdir(session_dir[i])[j] for j in range(0,len(os.listdir(session_dir[i])))])

In [3]:
sum(files[i][-3::]=="txt" for i in range(0,len(files)))/len(files)

1.0

In [5]:
transcripts=np.empty(0).astype(str)
for k in range(0,len(files)):
    transcripts=np.append(transcripts,open(files[k],"r",encoding="utf8").read())

In [8]:
session_years

array([1970., 1971., 1972., 1973., 1974., 1975., 1976., 1977., 1978.,
       1979., 1980., 1981., 1982., 1983., 1984., 1985., 1986., 1987.,
       1988., 1989., 1990., 1991., 1992., 1993., 1994., 1995., 1996.,
       1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017., 2018.])

In [9]:
sessions_per_year

array([ 70., 116., 125., 120., 129., 126., 134., 140., 141., 144., 149.,
       145., 147., 149., 150., 137., 149., 152., 154., 153., 156., 162.,
       168., 175., 178., 172., 181., 176., 181., 181., 178., 189., 188.,
       189., 192., 185., 193., 191., 192., 193., 189., 194., 195., 193.,
       194., 193., 194., 196., 196.])

In [10]:
country

array(['ALB', 'ARG', 'AUS', ..., 'ZAF', 'ZMB', 'ZWE'], dtype='<U32')

In [14]:
year=np.zeros(0)
for i in range(0,len(session_years)):
    year=np.append(year,np.repeat(session_years[i],sessions_per_year[i]))
    

array([1970., 1970., 1970., ..., 2018., 2018., 2018.])

In [19]:
data={"country":country,"year":year,"transcript":transcripts}

In [21]:
data=pd.DataFrame(data=data)

In [25]:
data.to_excel("All Trans.xlsx")